import test from 'node:test';
import assert from 'node:assert/strict';
import{newTic,ticMove,ticAI,ticResult,newDots,dotsMove,dotsAI,dotEdges,newCheckers,checkersMoves,checkersMove,checkersAI,customWord,wordMove,newWord,WORDS}from'../dist/rules.js';
test('tic-tac-toe wins, ties, and invalid moves',()=>{let s=newTic();for(const i of [0,3,1,4,2])s=ticMove(s,i);assert.equal(s.result.winner,1);assert.deepEqual(s.result.line,[0,1,2]);assert.equal(ticMove(s,8),null);assert.equal(ticMove(newTic(),-1),null);assert.equal(ticResult([1,2,1,1,2,2,2,1,1]).winner,'draw')});
test('tricky tic-tac-toe never loses against any human move sequence',()=>{let paths=0;function walk(s){if(s.result){assert.notEqual(s.result.winner,1);paths++;return}if(s.turn===2)walk(ticMove(s,ticAI(s,'tricky',()=>0)));else for(let i=0;i<9;i++)if(!s.board[i])walk(ticMove(s,i))}walk(newTic());assert.ok(paths>100)});
test('dots completes two boxes with a shared edge and keeps turn',()=>{let s=newDots(2);s.h=[1,2,1,2,0,0];s.v=[1,0,2,0,0,0];s.turn=1;s=dotsMove(s,'v',1);assert.deepEqual(s.boxes,[1,1,0,0]);assert.equal(s.lastScored,2);assert.equal(s.turn,1);assert.equal(dotsMove(s,'v',1),null)});
test('dots whole games terminate with every box claimed and legal AI edges',()=>{for(const n of [2,3,4]){let s=newDots(n);while(!s.result){const m=dotsAI(s,'tricky',()=>.3);assert.ok(dotEdges(s).some(e=>e.axis===m.axis&&e.index===m.index));s=dotsMove(s,m.axis,m.index)}assert.equal(s.moves,2*n*(n+1));assert.ok(s.boxes.every(Boolean))}});
function board(pieces,turn=1){const s=newCheckers(turn);s.board=Array(64).fill(0);for(const[i,p]of pieces)s.board[i]=p;s.repeats={};return s}
test('checkers starts with 12 pieces each and seven legal opening moves',()=>{const s=newCheckers();assert.equal(s.board.filter(p=>p===1).length,12);assert.equal(s.board.filter(p=>p===2).length,12);assert.equal(checkersMoves(s).length,7);assert.equal(checkersMove(s,40,49),null)});
test('checkers forces captures and continued jumps by the same piece',()=>{let s=board([[42,1],[33,2],[17,2],[46,1],[7,2]]);assert.deepEqual(checkersMoves(s),[{from:42,to:24,capture:33}]);s=checkersMove(s,42,24);assert.equal(s.board[33],0);assert.equal(s.forced,24);assert.equal(s.turn,1);assert.equal(checkersMove(s,46,37),null);s=checkersMove(s,24,10);assert.equal(s.board[17],0);assert.equal(s.forced,null);assert.equal(s.turn,2)});
test('checkers promotion ends the turn and a king can move backwards',()=>{let s=board([[17,1],[10,2],[12,2]]);s=checkersMove(s,17,3);assert.equal(s.board[3],-1);assert.equal(s.turn,2);assert.equal(s.forced,null);const k=board([[26,-1],[7,2]]);assert.ok(checkersMoves(k).some(m=>m.to===35));const p=board([[26,1],[7,2]]);assert.ok(!checkersMoves(p).some(m=>m.to===35))});
test('checkers detects a blocked opponent',()=>{const s=board([[17,1],[1,2],[10,1],[8,1]]);const next=checkersMove(s,17,24);assert.equal(next,null);const win=board([[17,1],[10,2]]);assert.equal(checkersMove(win,17,3).result.winner,1)});
test('checkers draw by repetition',()=>{let s=board([[56,-1],[7,-2]]);for(let round=0;round<3&&!s.result;round++){for(const[from,to]of [[56,49],[7,14],[49,56],[14,7]]){if(s.result)break;s=checkersMove(s,from,to)}}assert.equal(s.result.winner,'draw')});
test('computer checkers makes only legal moves through whole games',()=>{for(const level of ['gentle','tricky']){let s=newCheckers(),steps=0;while(!s.result&&steps<400){const m=checkersAI(s,level,()=>.37);assert.ok(checkersMoves(s).some(x=>x.from===m.from&&x.to===m.to));s=checkersMove(s,m.from,m.to);steps++}assert.ok(s.result,level+' game must finish')}});
test('word validation, repeated letters, duplicate guesses, win and loss',()=>{assert.equal(customWord('<script>'),null);assert.equal(customWord('two words'),null);let s=customWord('egg');s=wordMove(s,'G');assert.equal(wordMove(s,'G'),null);s=wordMove(s,'E');assert.equal(s.result.winner,1);assert.equal(wordMove(s,'X'),null);s=customWord('cat');for(const c of 'BDEFGHIJ')s=wordMove(s,c);assert.equal(s.result.winner,2)});
test('beginner word library stays short and avoids immediate repeats',()=>{assert.ok(WORDS.every(w=>/^[A-Z]{3,4}$/.test(w.word)&&w.picture&&w.clue));const a=newWord('Animals','',()=>0),b=newWord('Animals',a.word,()=>0);assert.notEqual(a.word,b.word);assert.equal(b.group,'Animals')});
